language: node_js
env:
  - JQUERY_VERSION=1.11.2
  - JQUERY_VERSION=2.1.3
before_install:
  - npm install -g grunt-cli bower
  - npm install
  - bower install
  - bower install jquery#$JQUERY_VERSION
script:
  - npm test
